# Esports LAN Infrastructure - Simple Configuration
# Version 2.0 - Streamlined for single-server deployments

# Organization Details
organization:
  name: "Your School Esports"
  short_name: "YSE"

# Proxmox Server Connection
proxmox:
  host: "192.168.1.5"              # Use IP address, not hostname
  user: "root@pam"                 # Standard Proxmox user
  password: ""                     # Fill this in, or use API token below
  
  # Alternative: API Token (more secure)
  # Create in Proxmox UI: Datacenter → Permissions → API Tokens
  api_token_id: ""                 # Format: user@realm!tokenname
  api_token_secret: ""             # The secret shown once
  
  node: "pve"                      # Your Proxmox node name
  storage: "local-lvm"             # Storage pool for VM disks

# Network Configuration
network:
  subnet: "192.168.1.0/24"
  gateway: "192.168.1.1"
  
  # Infrastructure Server IPs (must be outside DHCP range)
  pxe_server: "192.168.1.10"
  lancache_server: "192.168.1.11"
  file_server: "192.168.1.12"
  
  # DHCP Range for Client PCs
  dhcp_start: "192.168.1.100"
  dhcp_end: "192.168.1.254"
  
  # DNS (LANCache will be primary, this is fallback)
  dns_fallback: "8.8.8.8"

# VM Resource Allocation
# Adjust based on your server's capacity
resources:
  pxe_server:
    memory: 2048          # MB (2GB)
    cores: 2
    disk: 32              # GB
  
  lancache_server:
    memory: 16384         # MB (16GB)
    cores: 4
    disk: 500             # GB for OS
    cache_disk: 30000     # GB (30TB) for game cache
  
  file_server:
    memory: 8192          # MB (8GB)
    cores: 4
    disk: 100             # GB for OS
    data_disk: 5000       # GB (5TB) for user profiles

# Game Platforms to Cache
games:
  steam: true
  epic: true
  riot: true
  battlenet: false        # Enable if needed

# User Profile Settings
profiles:
  max_size_gb: 2          # Maximum profile size per user
  quota_warning: true     # Warn users when approaching limit

# Optional: Pre-create user accounts
# Leave empty to create manually after deployment
users: []
  # - username: player001
  #   password: changeme
  # - username: player002
  #   password: changeme

# Advanced Settings (usually don't need to change)
advanced:
  ssh_key_path: "~/.ssh/id_rsa.pub"  # SSH key for VM access
  timezone: "America/New_York"
  
  # Network bridge on Proxmox
  network_bridge: "vmbr0"
  
  # Enable if using VLANs
  vlan_id: null           # e.g., 100
  
  # Deployment options
  parallel_deploy: true   # Deploy all VMs simultaneously
  skip_updates: false     # Skip apt updates for faster deploy (not recommended)