version: '3.9'

# LANCache Docker Compose Configuration
# High School Esports LAN Infrastructure

services:
  # DNS Server - Intercepts game CDN domains
  lancache-dns:
    image: lancachenet/lancache-dns:latest
    container_name: lancache-dns
    restart: unless-stopped
    env_file:
      - lancache-dns.env
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - lancache
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Cache Server - Nginx-based caching proxy
  lancache:
    image: lancachenet/monolithic:latest
    container_name: lancache
    restart: unless-stopped
    env_file:
      - lancache.env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - lancache
    volumes:
      # Cache storage (this should be on a large disk)
      - /srv/lancache/data:/data/cache
      - /srv/lancache/logs:/data/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Optional: SNI Proxy for HTTPS passthrough
  sniproxy:
    image: lancachenet/sniproxy:latest
    container_name: sniproxy
    restart: unless-stopped
    ports:
      - "443:443/tcp"
    networks:
      - lancache
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Monitoring with Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: lancache-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - lancache
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - monitoring

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: lancache-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - lancache
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - monitoring

  # Optional: Log exporter for monitoring
  log-exporter:
    image: ghcr.io/nginxinc/nginx-prometheus-exporter:latest
    container_name: lancache-log-exporter
    restart: unless-stopped
    ports:
      - "9113:9113"
    networks:
      - lancache
    command:
      - '-nginx.scrape-uri=http://lancache:80/nginx_status'
    depends_on:
      - lancache
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - monitoring

networks:
  lancache:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data: